### ISSUE TITLE
Mai multe entitati 

### ISSUE THREAD

**Issue by gabimal** [cnecrea/infpro#1]
În primul rand salutare și mii de mulțumiri pentru aceasta integrare, este super tare ideea!
Voiam sa întreb dacă este posibila crearea de mai mulți senzori/entitati pe care le putem pune în dashboard. Momentan sunt doar Cutremur și Date analiză. După ce le pui pe acestea în dashboard fiecare dintre cele două au mai multe atribute. Aceste atribute pot fi cumva afișate ca și entitati? Aș fi interesat de exemplu să afișeze și data/ora producerii evenimentului, distanta și intensitatea.
Mulțumesc anticipat!

**Comment by cnecrea** [comment]
> În primul rand salutare și mii de mulțumiri pentru aceasta integrare, este super tare ideea! Voiam sa întreb dacă este posibila crearea de mai mulți senzori/entitati pe care le putem pune în dashboard. Momentan sunt doar Cutremur și Date analiză. După ce le pui pe acestea în dashboard fiecare dintre cele două au mai multe atribute. Aceste atribute pot fi cumva afișate ca și entitati? Aș fi interesat de exemplu să afișeze și data/ora producerii evenimentului, distanta și intensitatea. Mulțumesc anticipat!

Salut! Informațiile detaliate există deja, doar că probabil nu ai știut cum să le vizualizezi:

<img width="910" alt="image" src="https://github.com/user-attachments/assets/069ea91e-430c-49c2-8dc5-10e9eefd43ed" />



```yaml
type: entities
title: Monitorizare Cutremur
entities:
  - type: attribute
    entity: sensor.cutremur
    attribute: Magnitudine (ML)
    name: Magnitudine (ML)
  - type: attribute
    entity: sensor.cutremur
    attribute: Magnitudinea Momentului (Mw)
    name: Magnitudinea Momentului (Mw)
  - type: attribute
    entity: sensor.cutremur
    attribute: Ora locală
    name: Ora Locală
  - type: attribute
    entity: sensor.cutremur
    attribute: Latitudine
    name: Latitudine
  - type: attribute
    entity: sensor.cutremur
    attribute: Longitudine
    name: Longitudine
  - type: attribute
    entity: sensor.cutremur
    attribute: Adâncime (km)
    name: Adâncime (km)
  - type: attribute
    entity: sensor.cutremur
    attribute: Zonă
    name: Zonă
  - type: attribute
    entity: sensor.cutremur
    attribute: Intensitate
    name: Intensitate
  - type: attribute
    entity: sensor.cutremur
    attribute: Alertă
    name: Alertă
```

```yaml
type: entities
title: Analiză Date
entities:
  - type: attribute
    entity: sensor.date_analiza
    attribute: Oraș
    name: Oraș
  - type: attribute
    entity: sensor.date_analiza
    attribute: Județ
    name: Județ
  - type: attribute
    entity: sensor.date_analiza
    attribute: Distanță (km)
    name: Distanță (km)
  - type: attribute
    entity: sensor.date_analiza
    attribute: Accelerația maximă a solului
    name: Accelerația Max. a Solului
  - type: attribute
    entity: sensor.date_analiza
    attribute: Viteza maximă a solului
    name: Viteza Max. a Solului
  - type: attribute
    entity: sensor.date_analiza
    attribute: Intensitate
    name: Intensitate
  - type: attribute
    entity: sensor.date_analiza
    attribute: Intensitatea accelerației
    name: Intensitatea Accelerației
```
