### ISSUE TITLE
Eroare dupa o notificare de cutremur

### ISSUE THREAD

**Issue by alecsgeorge** [cnecrea/infpro#10]
### Ați citit secțiunea FAQ.md?

Da, am citit secțiunea FAQ.md și nu am găsit răspunsul la problema mea.

### Descrieți problema

Dupa ce am primit o notificare de cutremur ca s-a produs in jurul orei 17:00 ( pe site-ul oficial nu am vazut acest cutremur ) am primit o eroare in logs. Locuiesc in Bucuresti . 

### Versiunea integrării

2.0.0

### Loguri relevante

```yaml
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 5:04:44 PM (1 occurrences)
Last logged: 5:04:44 PM

Detected that custom integration 'infpro' sets option flow config_entry explicitly, which is deprecated at custom_components/infpro/config_flow.py, line 78: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/cnecrea/infpro/issues
```

### Ați încercat să dați restart?

Da

### Sistem de operare

home assistant os
