### ISSUE TITLE
erori in logs

### ISSUE THREAD

**Issue by alecsgeorge** [cnecrea/infpro#9]
### Ați citit secțiunea FAQ.md?

Da, am citit secțiunea FAQ.md și nu am găsit răspunsul la problema mea.

### Descrieți problema

De ceva timp am observat logs ca primesc mereu aceste mesaje, si nu stiu daca e normal sau care ar fi rezolvarea. Acele mesaje le primeam si inainte de update si dupa . 

### Versiunea integrării

1.0.0

### Loguri relevante

```yaml
Log details (WARNING)
This error originated from a custom integration.
Logger: custom_components.alerta_anm.sensor
Source: custom_components/alerta_anm/sensor.py:60
integration: Alerta ANM (documentation)
First occurred: 4:00:24 PM (29 occurrences)
Last logged: 4:13:24 PM

Nu există date disponibile: Nu exista date
```

### Ați încercat să dați restart?

Da

### Sistem de operare

home assistant os
